/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as StoreLocatorRouteImport } from './routes/store-locator'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PearlWithGoldRouteImport } from './routes/pearl-with-gold'
import { Route as PearlGuideRouteImport } from './routes/pearl-guide'
import { Route as OurStoryRouteImport } from './routes/our-story'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CraftsmanshipRouteImport } from './routes/craftsmanship'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuildComboRouteImport } from './routes/build-combo'
import { Route as BookAppointmentRouteImport } from './routes/book-appointment'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreLocatorRoute = StoreLocatorRouteImport.update({
  id: '/store-locator',
  path: '/store-locator',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PearlWithGoldRoute = PearlWithGoldRouteImport.update({
  id: '/pearl-with-gold',
  path: '/pearl-with-gold',
  getParentRoute: () => rootRouteImport,
} as any)
const PearlGuideRoute = PearlGuideRouteImport.update({
  id: '/pearl-guide',
  path: '/pearl-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const OurStoryRoute = OurStoryRouteImport.update({
  id: '/our-story',
  path: '/our-story',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CraftsmanshipRoute = CraftsmanshipRouteImport.update({
  id: '/craftsmanship',
  path: '/craftsmanship',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildComboRoute = BuildComboRouteImport.update({
  id: '/build-combo',
  path: '/build-combo',
  getParentRoute: () => rootRouteImport,
} as any)
const BookAppointmentRoute = BookAppointmentRouteImport.update({
  id: '/book-appointment',
  path: '/book-appointment',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/build-combo': typeof BuildComboRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/our-story': typeof OurStoryRoute
  '/pearl-guide': typeof PearlGuideRoute
  '/pearl-with-gold': typeof PearlWithGoldRoute
  '/signup': typeof SignupRoute
  '/store-locator': typeof StoreLocatorRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/build-combo': typeof BuildComboRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/our-story': typeof OurStoryRoute
  '/pearl-guide': typeof PearlGuideRoute
  '/pearl-with-gold': typeof PearlWithGoldRoute
  '/signup': typeof SignupRoute
  '/store-locator': typeof StoreLocatorRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/book-appointment': typeof BookAppointmentRoute
  '/build-combo': typeof BuildComboRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/craftsmanship': typeof CraftsmanshipRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/order-success': typeof OrderSuccessRoute
  '/our-story': typeof OurStoryRoute
  '/pearl-guide': typeof PearlGuideRoute
  '/pearl-with-gold': typeof PearlWithGoldRoute
  '/signup': typeof SignupRoute
  '/store-locator': typeof StoreLocatorRoute
  '/wishlist': typeof WishlistRoute
  '/product/$id': typeof ProductIdRoute
  '/shop/$slug': typeof ShopSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/book-appointment'
    | '/build-combo'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/craftsmanship'
    | '/dashboard'
    | '/login'
    | '/order-success'
    | '/our-story'
    | '/pearl-guide'
    | '/pearl-with-gold'
    | '/signup'
    | '/store-locator'
    | '/wishlist'
    | '/product/$id'
    | '/shop/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/book-appointment'
    | '/build-combo'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/craftsmanship'
    | '/dashboard'
    | '/login'
    | '/order-success'
    | '/our-story'
    | '/pearl-guide'
    | '/pearl-with-gold'
    | '/signup'
    | '/store-locator'
    | '/wishlist'
    | '/product/$id'
    | '/shop/$slug'
  id:
    | '__root__'
    | '/'
    | '/book-appointment'
    | '/build-combo'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/craftsmanship'
    | '/dashboard'
    | '/login'
    | '/order-success'
    | '/our-story'
    | '/pearl-guide'
    | '/pearl-with-gold'
    | '/signup'
    | '/store-locator'
    | '/wishlist'
    | '/product/$id'
    | '/shop/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BookAppointmentRoute: typeof BookAppointmentRoute
  BuildComboRoute: typeof BuildComboRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRoute
  CraftsmanshipRoute: typeof CraftsmanshipRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  OurStoryRoute: typeof OurStoryRoute
  PearlGuideRoute: typeof PearlGuideRoute
  PearlWithGoldRoute: typeof PearlWithGoldRoute
  SignupRoute: typeof SignupRoute
  StoreLocatorRoute: typeof StoreLocatorRoute
  WishlistRoute: typeof WishlistRoute
  ProductIdRoute: typeof ProductIdRoute
  ShopSlugRoute: typeof ShopSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store-locator': {
      id: '/store-locator'
      path: '/store-locator'
      fullPath: '/store-locator'
      preLoaderRoute: typeof StoreLocatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pearl-with-gold': {
      id: '/pearl-with-gold'
      path: '/pearl-with-gold'
      fullPath: '/pearl-with-gold'
      preLoaderRoute: typeof PearlWithGoldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pearl-guide': {
      id: '/pearl-guide'
      path: '/pearl-guide'
      fullPath: '/pearl-guide'
      preLoaderRoute: typeof PearlGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-story': {
      id: '/our-story'
      path: '/our-story'
      fullPath: '/our-story'
      preLoaderRoute: typeof OurStoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/craftsmanship': {
      id: '/craftsmanship'
      path: '/craftsmanship'
      fullPath: '/craftsmanship'
      preLoaderRoute: typeof CraftsmanshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-combo': {
      id: '/build-combo'
      path: '/build-combo'
      fullPath: '/build-combo'
      preLoaderRoute: typeof BuildComboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book-appointment': {
      id: '/book-appointment'
      path: '/book-appointment'
      fullPath: '/book-appointment'
      preLoaderRoute: typeof BookAppointmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BookAppointmentRoute: BookAppointmentRoute,
  BuildComboRoute: BuildComboRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRoute,
  CraftsmanshipRoute: CraftsmanshipRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  OurStoryRoute: OurStoryRoute,
  PearlGuideRoute: PearlGuideRoute,
  PearlWithGoldRoute: PearlWithGoldRoute,
  SignupRoute: SignupRoute,
  StoreLocatorRoute: StoreLocatorRoute,
  WishlistRoute: WishlistRoute,
  ProductIdRoute: ProductIdRoute,
  ShopSlugRoute: ShopSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
